[package]
name = "contracts"
version = "0.1.0"
edition = "2023_11"

[dependencies]
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }

[[target.starknet-contract]]
casm = true

[tool.fmt]
sort-module-level-items = true